source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

target 'APDataSources_Example', :exclusive => true do
  pod "APDataSources", :path => "../"
  pod 'APCDController'
end

target 'APDataSources_Tests', :exclusive => true do
  pod "APDataSources", :path => "../"
  pod 'Expecta'
  pod 'OCMock'
  
end
