source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'APDataSources_Example', :exclusive => true do
  pod "APDataSources", :path => "../"
end

target 'APDataSources_Tests', :exclusive => true do
  pod "APDataSources", :path => "../"

  
end
